player createDiarySubject ["Butts Changes","Butts Changes"];

player createDiaryRecord ["Butts Changes", ["Mission Reputation Definitions", "The repuation system determines what events may happen based on the number value. This could mean more things like bombers and militia in towns. Example of good reputation means you are more likely to get truthful intel. When asking a civilian about your rep, his responses are based on this:<br/><br/>Very Low > 200<br/>Low = 200 to 499<br/>Normal = 500 to 749<br/>High = 750 or more<br/><br/>Currently testing a mission failure trigger if reputation is -500"]
];

player createDiaryRecord ["Butts Changes", ["FOB Changes", "Teleporting and Redeploy<br/>When interacting with FOB flag, player can also teleport to another FOB or teleport back to base. When teleporting back to base, there is a cooldown of 10 minutes before it can be used again.<br/><br/>Arsenal<br/>Player has full arsenal available when interacting with FOB flag."]
];

player createDiaryRecord ["Butts Changes", ["BTC Create Object changes", "The BTC Create Object (or crate you interact with to repair wrecks and rearm) has been modified to add a new Butts submenu.<br/><br/>Spawn Autonomous X<br/>This allows a player with an engineer variable to spawn an autonomus MG, GMG, or Praetor. This calls a script to spawn a autonomous object with a 'crew' so that a player can access it with a UAV terminal. If one were to request a regular autonomous turret from the statics list, it would spawn one with out the so-called crew, and a player can't access it with UAV terminal.<br/><br/>5 minute Full rearm<br/>This allows someone with an engineer variable to rearm and repair the vehicle on the pad. This takes 5 minutes."]
];

player createDiaryRecord ["Butts Changes", ["Butts Board", "A TV monitor has been added to the base area that only someone with an officer variable can successfully interact with.<br/><br/>Request X UAV<br/>This will check the area for existing UAVs, and if there are none, spawn the desired UAV type with ai 'crew' so that someone with a UAV terminal can control it. The UAV will be spawned over the base and flying.<br/><br/>Replace TOW on Humvee<br/>Since there are no RHS TOW humvees, this hacky script attaches a static TOW launcher to the roof of an unarmed Humvee. It looks goofy but it is a compromise to fulfill a role.<br/><br/>Refuel Fuel Truck<br/>You can either destroy and repair the wreck of your fuel truck if its fuel cargo runs out, or run this script to refuel its cargo so it can refuel other vehicles."]
];

player createDiaryRecord ["Butts Changes", ["Military Cargo HQ", "A Military Cargo HQ has been added to the base area that is an ACE Medical Facility. That means that this upgrades the medic training of all soldiers inside so non-medics can perform actions like blood transfusions. A medical crate has also been placed inside with 10k of each of the basic medical supplies so players have easy access to stuff to patch each other up."]
];

player createDiaryRecord ["Butts Changes", ["General Changes", "Overall Concept<br/><br/>The overall idea of these changes is to provide better playability for situations where playercount is low, and to support a combined arms to fight a tougher enemy.<br/><br/>Base<br/><br/>The base has been moved to the Military portion of the main airport to accomodate diverse vehicles. <br/><br/>Many of the objects in the base area have had a lightpoint script applied to them so they are lit at night.<br/><br/>BTC service points have been added. The vehicle service point is the regular BTC create point, and the aircraft service point is closer to the runway. Please note that especially in the case of Aircraft service, trying to rearm an RHS vehicle may cause the module to not work (and lock you in the vehicle forever).<br/><br/>Instead of searching for unit type for Butts scripts, it looks for a variable. So if you wanted to give multiple people the ability to call a side mission or other butts commands, just add the variable to the player as an admin.<br/><br/>The Ask Reputation script has been modified to tell you what the actual rep number is.<br/><br/>The city script has been updated so that more civilians spawn in a city, but to make it easier for PC's to handle, waypoints per civilian are decreased.<br/><br/>There are multiple safe zones added where things should not spawn to accommodate the fact that the airport runway will be used.<br/><br/>Many of the vehicles have been changed, and some are added- such as the sea vehicles.<br/><br/>Big Trucks can tow just about anything, even Planes and Helicopters. This makes it so if air vehicles crash near trees and buildings and a lift helicopter can't get low enough without crashing, a vehicle can be brought to tow it away.<br/><br/>The actual reputation value in numerical format is displayed."]
];